### ISSUE TITLE
zgrab2 grab http protocol will be stuck when grab port on 8000

### ISSUE THREAD

**Issue by leaixian** [zmap/zgrab2#163]
example: http://39.107.249.96:8000 ,when using zgrab2 to grab this banner it will be stuck and can not finished, through wireshark  I found that this device is continuously send data to my device ,but it is not HTTP data. How can I solve it ?Thank you!
![1536142601 1](https://user-images.githubusercontent.com/15059068/45087328-0e3d8d80-b138-11e8-8dcc-a35ed20f1730.png)

**Comment by justinbastress** [comment]
@leaixian zgrab / zgrab2 are application-layer scanners that scan details about a specific protocol given ahead of time; if you just want to check that a port is open, and not if it is running HTTP, then https://github.com/zmap/zmap may be what you are looking for.

As for it being stuck, the default timeout is 10s for connection / reads, but since the server is sending a response more frequently than that, it is staying open -- and that does need to be addressed, i.e. by adding a timeout for the entire session and/or recognizing immediately that the response is not valid HTTP.
