### ISSUE TITLE
tls handshake failure ?

### ISSUE THREAD

**Issue by chushuai** [zmap/zgrab2#281]
It can be accessed using a browser

https://1.179.232.207:1080/

{"ip":"1.179.232.207","data":{"tls":{"status":"unknown-error","protocol":"tls","timestamp":"2020-11-16T03:51:45-05:00","error":"remote error: handshake failure"}}}

Certificate information

-----BEGIN CERTIFICATE-----
MIIELTCCAxWgAwIBAgIJAP3YW6AGnB7OMA0GCSqGSIb3DQEBBQUAMGwxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRAwDgYDVQQHEwdTYW5Kb3NlMRAw
DgYDVQQKEwdORVRHRUFSMRAwDgYDVQQLEwdORVRHRUFSMRIwEAYDVQQDEwlsb2Nh
bGhvc3QwHhcNMTUwNTIyMDk0MjUwWhcNMzUwNTE3MDk0MjUwWjBsMQswCQYDVQQG
EwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEQMA4GA1UEBxMHU2FuSm9zZTEQMA4G
A1UEChMHTkVUR0VBUjEQMA4GA1UECxMHTkVUR0VBUjESMBAGA1UEAxMJbG9jYWxo
b3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxBOflTqGpXaQ4PG0
5D4JR+LlE+SP8IoaZbkqsZZ/bYHrb5HPHzxDCCfZxtzEXg1hleDEQMvO0IQY0+Ay
+qxtHInljG8ZMm8z53C3FQbSuMc2AcbWzmxMRSnkxH8+MCHzddlf88t2WEUQHItG
wnjOou4PNQVGfacSmtRzWX6R3waYUBN+m7EKrILhLsG3xXo0EyKbV2etPNHEIImR
/GiFW4QCkwvII8c9XYV4xflxdVYKULk1cr8Ni6yWysw53UrbJ/hg0XlPtccT3yM9
P8DUccDbusU4HNxW+Yn0mwJ7f5fqthzz212wUHEjdU00uSirQwRGe/j6jF+vr7FV
WQgmwQIDAQABo4HRMIHOMB0GA1UdDgQWBBR06hHiwzVi5uqeDVGL8KROGO0XczCB
ngYDVR0jBIGWMIGTgBR06hHiwzVi5uqeDVGL8KROGO0Xc6FwpG4wbDELMAkGA1UE
BhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExEDAOBgNVBAcTB1Nhbkpvc2UxEDAO
BgNVBAoTB05FVEdFQVIxEDAOBgNVBAsTB05FVEdFQVIxEjAQBgNVBAMTCWxvY2Fs
aG9zdIIJAP3YW6AGnB7OMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEB
ABfmTjwjqTKsNzCe793gpyX9B/bimZ7Tm8oiHESzvFa7IPtCcwb/rpASz/pr/WO2
M5GxY2KbqzVgXAIqItuBc/O0UAOOJwVMVukDN7gtiINpORj4T3ElPeaXFv7314vw
0iR/EVE/koDb1DtqQKjfNvCeGg2cIvQ+i554xGO9artoWfb0NfwIrSN5+oOHycjk
NeJBgsNt5OrkYMJgWoICRmY1S3pdVbGsA4PFYZQWLCQN2OruPHfxx8JQkps+iYlQ
DuKkn85wOn2imFvSUa5qSfoyeqxyvJ2L6Yl2OArabyxqLCqT8XYJUc7eHy+E7T3a
Lfxw6vLKBiraX7YcsYBCQ2s=
-----END CERTIFICATE-----

**Comment by mzpqnxow** [comment]
What I suggest you do:

1. Capture a successful negotiation with Wireshark when connecting using a browser, right click one of the packets and select "decode as" -> "ssl" for both ports
2. Do the same thing, but using zgrab2 to make the connection
3. Compare and analyze the two Wireshark captures (specifically, the decoded SSL/TLS protocol messages)

If you don't know enough yourself to analyze the difference and diagnose the issue, paste the two images from Wireshark here (or in a text format) and I'll take a look

**Comment by mzpqnxow** [comment]
I took a quick look and I'm seeing (when using zgrab2, as well as Firefox ESR) the client hello is sent and the server is immediately responding with fatal alert 0x28, which is `SSL3_ALERT_HANDSHAKE_FAILURE`

I see this behavior occur for `openssl` cli as well. This is definitely not a problem specific to zgrab2/golang ssl/tls implementation. There's something wacky with that device that some versions of Chrome seem to be able to work around

You can force the correct cipher suite and get a response using the following:

```
echo 1.179.232.207 | zgrab2 http -p 1080 --use-https --max-redirects=5 --retry-https --cipher-suite=9d
```

There seems to be something off about how the cipher-suite negotiation is working

After some testing and observing how Chrome was making it work, I noticed that ultimately it was choosing `TLS_RSA_WITH_AES_256_GCM_SHA384` as the cipher-suite- `zgrab2` takes a list of cipher-suites as ASCII hex integers. In this case, `0x9d` is the value that represents `TLS_RSA_WITH_AES_256_GCM_SHA384`

The device will also accept `TLS_RSA_AES_256_CBC_SHA256`, which is `--cipher-suite=3d`

Or you could specify as a list, `--cipher-suite=3d,9d`

It would be nice if this "just worked" without having to explicitly specify any cipher-suites, but as I said, the issue here doesn't seem to be in `zgrab2`- it seems to be in the golang SSL/TLS libraries. It's possible that the latest version of golang ssl/tls libraries can handle this some way. It's still not obvious to me whether this is unusual behavior by that device, or standards violating behavior, but it's possible newer golang can handle it.

For that reason, I would say any work that would "fix" this would be *related* to #252- which is dependent upon https://github.com/zmap/zcrypto/issues/212

If that is the case, this is a big effort, and is not guaranteed to fix this specific problem.

Not sure if this is helpful for you or not. Someone else can probably chime in and correctly me on any of the pseudo-analysis here- I'm not too experienced with golang and haven't looked at all at the SSL/TLS implementation, though I'm curious enough now to take a look...

**Comment by mzpqnxow** [comment]
Note, another workaround here would be using one of the cipher-suite profiles that zgrab2 has for the http module- this isn't too clearly documented, but the following also works:

```
echo 1.179.232.207 | zgrab2 http -p 1080 --use-https --max-redirects=5  --cipher-suite=safari-only
```

**Comment by mzpqnxow** [comment]
In conclusion, this behavior occurs because the default cipher-suite list in zgrab2 does not include either of the two cipher-suites that the device requires for successful negotiation. I think you can close this, there's no bug. However, I have opened up an issue in both zcrypto and zgrab2 to see if a cleaner method can be added that will provide more portable SSL/TLS negotiation, without having to specify a long list of cipher-suite ids

**Comment by engn33r** [comment]
Kudos to @mzpqnxow for paving the way for ZGrab2 to better support HTTP/HTTPS. The suggestion to use `zgrab2 http --use-https -p 443 --cipher-suite=safari-only` did the trick. I thought port 443 would be implied by `use-https`, but I suppose not. For reference, removing the `--max-redirects=5` argument didn't impact my results during my brief test.

**Comment by mzpqnxow** [comment]
@chushuai you can probably close this out now- if the safari workaround doesn't help you, #236 should once it's merged. Or you can check out my branch until it's officially merged (https://github.com/mzpqnxow/zgrab2/tree/feature/portable-suites)

thanks @engn33r, I pass the kudos on to the zmap devs who have been really great to work with on just about every issue so far
