### ISSUE TITLE
Add port field to input format

### ISSUE THREAD

**Issue by burpheart** [zmap/zgrab2#344]
zgrab2 cannot simply import the results of other scanners.
Each ip may have a large number of different ports and not just one or a few fixed ports.

**Comment by mzpqnxow** [comment]
> zgrab2 cannot simply import the results of other scanners.
> 
> Each ip may have a large number of different ports and not just one or a few fixed ports. 

This is already supported and can be done using the CSV-style target file with triggers/tags. Each trigger should have a corresponding ini file specifying the module and port for that trigger. You can then invoke 'zgrab2' with the 'multi' module, and specify the targets file and respective ini file

See #221 for an example of how I do this. The easiest way to do it (while avoiding issues 'zgrab2' has when loading extremely large target and ini files) is to have one ini file per-port. You then specify the trigger in the target file (the trigger will effectively represent the port for that host)

I feel that triggers and the CSV-style target format is under-utilized, but absolutely critical for certain usage patterns. As an example (my use-case) when looking at large target sets, with varying ports, where some ports benefit from specific settings. For example, for port 80, you may want 'retry-https', while for port 443, you may want 'use-ssl'

This is a bit more work than what you may have had in mind, but it's a one-time effort to write the script

While I originally thought the solution you described would be best and simple to implement (basically, allowing the user to specify <host>:<port> for each target, rather than <host>) I learned after working a bit on the code that it is fundamentally incompatible with that approach. It's not an oversight, it was a design decision from what I can tell, and it has both good and bad tradeoffs

Hope this is helpful

**Comment by mzpqnxow** [comment]
I think this can be closed
